export const en = {
    lang: 'en',
    homePage: 'Home',
    aboutPage: 'About us',
    servicePage: 'Services',
    portfolioPage: 'Portfolio',
    contactPage: 'Contact',
    devisBtn: 'Request a quote',
    mainTitle: 'Take The Right Road',
    intro: "Anytime & Anywhere is your business and investment advisor.",
    readMore: 'Read More',
    featuresTitle: 'Our approach',
    featuresParag: 'Description of the process to follow in your project',
    design: 'Design',
    development: 'Development',
    responsive: 'Responsive',
    seo: 'SEO',
    dataVisualTitle: 'Data analysis',
    dataTitle1: 'OUR TEAM',
    dataParag1: "Anytime & Anywhere holds as an MBM with focus on international business and has extensive experience in operations and business developement. Our core skills are process optimisation, web design, and marketing. Our business administration background means we always keep an eye on ROI and CPA, all while being able to comeup with creative solutions. As an operations professional, we enjoy ensuring that things run smoothly and create operation strategy to keep our clients on-track even after mimosa's work id done. We are trilanguage speakers whith stong knowledge of french-speaking markets.",
    dataTitle2: '02. STRATEGY',
    dataParag2: 'After a diagnostic phase, we will set up an action plan adapted to your needs.',
    itSolutionTitle: 'IT Solutions',
    itSolutionParag: 'We collaborate with you to create new value through digital transformation. We have specialists at your service.',
    serviceTitle: 'Our services',
    service1: 'Marketing Strategy',
    service2: 'Digital Marketing',
    service3: 'Graphic Design',
    service4: 'Web & Mobile Development',
    service1Point1: 'Communication strategy',
    service1Point2: 'Media plan',
    service1Point3: 'Advertising campaign',
    service2Point1: 'Websites SEO',
    service2Point2: 'Social Media',
    service2Point3: 'Sponsoring',
    service3Point1: 'Identity, Logo, Visit Card ...',
    service3Point2: 'Posters, Catalog, Menu ...',
    service3Point3: 'Websites & Applications design',
    service4Point1: 'Websites Development',
    service4Point2: 'Web Apps Development',
    service4Point3: 'Mobile Apps Development',
    managementServiceTitle: 'Service management',
    managementServiceParag: 'The efficiency and speed of transforming raw data into reliable and useful information.',
    webAnalyticsTitle: 'Web Analytics',
    webAnalyticsParag: 'We improve the efficiency and monitor the success of your website. We can deduce measures that aim to generate a positive development according to your objectives.',
    processTitle: 'No hidden cost, you choose the rate that suits you',
    processParag: "With our subscription plans, your launch cash is spared, and we charge our services to the maximum amount on order: you pay when it works!",
    ourPricesBtn: 'Our Prices',
    contactTitle: 'Get In Touch',
    contactParag: 'We align leaders around a shared purpose and strategic story that catalyzes their business and brand to take action.',
    adressTitle: "Adress",
    adress: "Street Ribat, building Meliane, La corniche 4000 Sousse, Tunisia",
    emailTitle: "Email",
    email: "contact@anytime4anywhere.fr",
    phoneTitle: "Call us",
    phone: "+21654563326",
    copyright: "2021 © Anytime & Anywhere",
    ourTeamTitle: 'Our team',
    about: "Anytime & Anywhere's mission is to support its clients in the development of their marketing strategies, by providing them with creative concepts and a range of innovative solutions tailored to their needs. Digital Communication offers you infinite possibilities, Our agency uses each one to sublimate you. Our marketing agency based in Sousse, Tunisia, offers you more than a web service, a global communication offer.",
    nizar: 'Nizar Jerfel',
    nizarFunction: 'CEO',
    faycel: 'Faycel Yousfi',
    faycelFunction: 'Technical manager',
    maamoun: 'Maamoun Grissa',
    maamounFunction: 'Manager',
    kawther: 'Kawther Mehrez',
    kawtherFunction: 'Marketing manager',
    elhem: 'Elhem Missaoui',
    elhemFunction: 'Developer',
    houssem: 'Houssem Jbely',
    houssemFunction: 'Designer',
    contactUs: "Contact us",
    ourPortfolio: "Our portfolio",
    contactName: "Name",
    contactEmail: "Email",
    contactPhone: "Phone",
    contactMessage: "Message",
    sendBtn: "Send",
    contactBtn: "Contact us",
    feedback_message: "Message sent successfully",
    feedback_error: "Error, try again later please",
    whatsappMessage: "Welcome to Anytime Anywhere is a digital transformation consulting firm, how can we help you?",
    jobCity: "Sousse",
    jobSelect: "Select",
    jobSelected : "Selected",
    jobSelectFile: "Select your resume",
    coverLettre: "Cover letter",
    jobSelectedHolder: "Job selected",
    joinProcess: "Select a job and fill the form",
    marketingStrategy: "Marketing strategy",
    strategyP1: "A marketing strategy studies and determines really the advantages and the disadvantages of companies in order to set up a business plan for the near and long run.",
    strategyP2: "A good marketing strategy is necessary for a company to organize intelligently its plans,specially when strong concurrency.",
    strategyP3: "",
    segmentation: "Segmentation",
    targeting: "Targeting",
    positioning: "Positioning",
    smartGoals: "Smart goals",
    marketWatch: "Market watch and study",
    competitiveIntelligence: "Competitive intelligence",
    marketingTarget: "Identification of the marketing target",
    marketingPosition: "Marketing position",
    communicationStrategy: "Communication strategy",
    digitalMarketing: "Digital Marketing",
    seaSeo: "SEA & SEO",
    performanceMarketing: "Performance Marketing",
    emailing: "Loyalty and prospecting emailing",
    marketingPub: "Web & mobile advertising",
    marketingMedia: "Digital integrated into the media",
    marketingbtob: "Marketing digital B-to-B, CRM",
    menuServices: "Services",
    graphicDesign: "Graphic design",
    visualIdentity: "Visual identity",
    graphicaCharter: "Graphical charter",
    paperSupports: "Paper Supports",
    exibitionSupports: "Exibition supports",
    editingLayout: "Editing and layout",
    UiUxDesign: "Ui & Ux Design",
    developmentPageTitle: "Web & Mobile development",
    landingPages: "Landing Pages",
    portfolioWebsites: "Portfolio websites",
    catalogWebsites: "Catalog websites",
    eCommerce: "E-commerce platforms",
    webApps: "Web applications",
    mobileApps: "Mobile applications",
    quizNote: "The quote will be sent by email",
    days: "Days",
    requestQuote: "Request a quote",
    quoteDesign: "Design",
    quoteDevelopment: "Development",
    quoteMarketing: "Marketing",
    quizDetails: "Details",

    commercialProspecting: "Commercial Prospecting",
    service5: 'Commercial Prospecting',
    commercialP1: "It proposes to take in hand all the actions necessary for",
    commercialP2: "Business development",
    commercialStrategy: "Commercial strategy",
    multichannelProspecting: "Multichannel prospecting",
    customerLoyalty: "Customer Loyalty",
    conquerNewMarket: "Conquer New Market",

    prospectingP: "Experts in commercial prospecting, Anytime & anywhere specializes in the detection of business opportunities with high added value and in making qualified B-to-B meetings. To guarantee its efficiency and quality.",

    reviewsTitle: 'Clients reviews',
    
    portfolio: [
        {
            name: "Valorant Boosting",
            photo: "valorant.png",
            url: "https://valorantboosting.herokuapp.com/",
        },
        {
            name: "DNL Deco",
            photo: "dnl.png",
            url: "https://dnl-deco.herokuapp.com/",
        },
        {
            name: "Dali Market",
            photo: "dalimarket.png",
            url: "https://dalimarket.tn/",
        },
        {
            name: "Pro Artl",
            photo: "pro-artl.png",
            url: "https://pro-artl.ru/",
        },
        {
            name: "Auto Dom Kst",
            photo: "autodomkst.png",
            url: "",
        },
        {
            name: "Barrist",
            photo: "barrist.png",
            url: "https://barrist.ru/",
        },
        {
            name: "Volkswagen Costanai",
            photo: "volkswagen-costanai.png",
            url: "https://vw.autodomkst.kz/",
        },
        {
            name: "Volkswagen Almaty",
            photo: "volkswagen-almaty.png",
            url: "https://volkswagen-almaty.kz/",
        },
        {
            name: "Retail Comiten",
            photo: "retail-comiten.png",
            url: "https://retail.comiten.ru/",
        },
        {
            name: "Zavodskaya Plitka",
            photo: "zavodskaya-plitka.png",
            url: "https://www.zavodskaya-plitka.ru/",
        },
        {
            name: "Aidapraznik",
            photo: "aidapraznik.png",
            url: "http://www.aidaprazdnik-dedmoroz.ru/",
        },
        {
            name: "Bahitgul Hotel",
            photo: "bahitgul.png",
            url: "https://bahitgul.com/",
        },
    ],

    jobs: [
        {
            ref: "WD0821",
            title: "Web Developer",
            desc: "Full Stack developer, extremely versatile and able to take charge of the entire development process to provide websites and web & mobile applications.",
            skills: [
                'Html', 'Css', 'JavaScript', 'ReactJS', 'NodeJs'
            ]
        },
        {
            ref: "DS0821",
            title: "Designer",
            desc: "Innovative designer who can create a complete graphic charter for a brand, ui and ux design and video editing.",
            skills: [
                'Html', 'Css', 'JavaScript', 'ReactJS', 'NodeJs'
            ]
        },
        {
            ref: "CS0821",
            title: "Commercial",
            desc: "Responsible for the sales cycle, you deploy an intensive prospecting strategy and support prospects in defining their needs.",
            skills: [
                'Html', 'Css', 'JavaScript', 'ReactJS', 'NodeJs'
            ]
        }
    ]
}

export const fr = {
    lang: 'fr',
    homePage: 'Acceuil',
    aboutPage: 'Qui sommes-nous?',
    servicePage: 'Services',
    portfolioPage: 'References',
    contactPage: 'Contact',
    devisBtn: 'Demander un devis',
    mainTitle: 'Take The Right Road',
    intro: "Anytime & Anywhere est votre conseiller pour les affaires et l'investissement.",
    readMore: 'Lire la suite',
    featuresTitle: 'Notre démarche',
    featuresParag: 'Description du processus pour transformer votre entreprise',
    design: 'Conception',
    development: 'Développement',
    responsive: 'Responsive',
    seo: 'SEO',
    dataVisualTitle: "L'analyse des données",
    dataTitle1: 'NOTRE ÉQUIPE',
    dataParag1: 'Notre équipe créative, Agile et organisée est dévouée à la réussite de vos projets. Notre différence réside dans notre capacité à toujours proposer des solutions. Notre team vous assure un suivi irréprochable du début à la fin de la commande.',
    dataTitle2: '02. STRATEGIE',
    dataParag2: "Après une phase de diagnostic, nous mettrons en place un plan d'action adapté à vos besoins",
    itSolutionTitle: 'Solutions informatiques',
    itSolutionParag: 'Nous collaborons avec vous pour créer une nouvelle valeur grâce à la transformation digitale. Nous avons des spécialistes à votre service.',
    serviceTitle: 'Nos services',
    service1: 'Stratégie Marketing',
    service2: 'Marketing Digital',
    service3: 'Conception Graphique',
    service4: 'Développement Web & Mobile',
    service1Point1: 'Stratégie de communication',
    service1Point2: 'Plan média',
    service1Point3: 'Campagne publicitaire',
    service2Point1: 'Référencement de sites Web (SEO)',
    service2Point2: 'Réseau Sociaux',
    service2Point3: 'Sponsoring',
    service3Point1: 'Identité, Logo, Carte de Visite...',
    service3Point2: 'Affiches, Brochures, Menu...',
    service3Point3: 'Design de sites web et applications',
    service4Point1: 'Développement de sites Web',
    service4Point2: "Développement d'applications Web",
    service4Point3: "Développement d'applications mobiles",
    managementServiceTitle: 'Gestion de service',
    managementServiceParag: "L'efficacité et la rapidité de transformation des données brutes en informations fiables et utiles.",
    webAnalyticsTitle: 'Analyse web',
    webAnalyticsParag: "Nous améliorons l'efficacité et surveillons le succès de votre site Web. Nous pouvons en déduire des mesures qui visent à générer un développement positif en fonction de vos objectifs.",
    processTitle: 'Pas de coût caché, vous choisissez le tarif qui vous convient',
    processParag: "Avec nos formules d'abonnement, votre trésorerie de lancement est ménagée, et nous facturons au maximum nos prestations à la commande : vous payez quand ça marche !",
    ourPricesBtn: 'Nos Tarifs',
    contactTitle: 'Entrer en contact',
    contactParag: "Nous alignons les dirigeants autour d'un objectif commun et d'une histoire stratégique qui catalyse leur entreprise et leur marque à agir.",
    adressTitle: "Adresse",
    adress: "Rue ribat immeuble Meliene la corniche 4000 Sousse, Tunisie",
    emailTitle: "E-mail",
    email: "contact@anytime4anywhere.fr",
    phoneTitle: "Appeler nous",
    phone: "+21654563326",
    copyright: "2021 © Anytime & Anywhere",
    ourTeamTitle: 'Notre équipe',
    about: "Anytime & Anywhere se donne comme mission d’accompagner ses clients dans le développement de leurs stratégies marketing, en leur posant des concepts créatifs et une panoplie des solutions novatrices adaptées à leurs besoins. La Communication Digitale vous offre des possibilités infinies, Notre agence exploite chacune entre elles pour vous sublimer. Notre agence du marketing basée à Sousse, Tunisie, vous propose plus qu’un service web, une offre globale de communication.",
    nizar: 'Nizar Jerfel',
    nizarFunction: 'CEO',
    faycel: 'Faycel Yousfi',
    faycelFunction: 'Responsable Technique',
    maamoun: 'Maàmoun Grissa',
    maamounFunction: 'Directeur',
    kawther: 'Kawther Mehrez',
    kawtherFunction: 'Responsable Marketing',
    elhem: 'Elhem Missaoui',
    elhemFunction: 'Développeur',
    houssem: 'Houssem Jbely',
    houssemFunction: 'Designer',
    contactUs: "Contacter nous",
    ourPortfolio: "Notre portfolio",
    contactName: "Nom & Prénom",
    contactEmail: "Email",
    contactPhone: "Téléphone",
    contactMessage: "Message",
    sendBtn: "Envoyer",
    contactBtn: "Contacter nous",
    feedback_message: "Message envoyé avec succès",
    feedback_error: "Erreur, réessayez plus tard s'il vous plaît",
    whatsappMessage: "Bienvenue à Anytime Anywhere est une cabinet de conseil en transformation digitale.Comment pouvons-nous vous aider?",
    jobCity: "Sousse",
    jobSelect: "Sélectioner",
    jobSelected : "Sélectionné",
    jobSelectFile: "Sélectioner votre résumer",
    coverLettre: "Lettre de motivation",
    jobSelectedHolder: "Poste sélectionneé",
    joinProcess: "Sélectionnez un emploi et remplissez le formulaire",
    marketingStrategy: "Stratégie marketing",
    strategyP1: "La stratégie marketing prend en compte l'environnement d'une entreprise, détermine ses forces et ses faiblesses afin d'établir des business plans à court et long terme.",
    strategyP2: "Une stratégie marketing bien établie est indispensable à toute entreprise pour mener ses actions avec cohérence et intelligence.",
    strategyP3: "Parce que pour rester compétitif, il est hors de question de devenir aveugle !",
    segmentation: "Segmentation",
    targeting: "Ciblage",
    positioning: "Positionnement",
    smartGoals: "Objectifs intelligents",
    marketWatch: "Veille et étude de marché",
    competitiveIntelligence: "Veille concurrentielle",
    marketingTarget: "Identification de la cible marketing",
    marketingPosition: "Position marketing",
    communicationStrategy: "Stratégie de communication",
    digitalMarketing: "Digital Marketing",
    seaSeo: "SEA & SEO",
    performanceMarketing: "Performance Marketing",
    emailing: "Emailing de fidélisation et de prospection",
    marketingPub: "Publicité web & mobile",
    marketingMedia: "Le digital intégré aux médias",
    marketingbtob: "Marketing digital B-to-B, CRM",
    menuServices: "Services",
    graphicDesign: "Design graphique",
    visualIdentity: "Identité visuelle",
    graphicaCharter: "Charte graphique",
    paperSupports: "Support papier",
    exibitionSupports: "Support d'exposition",
    editingLayout: "Edition et mise en page",
    UiUxDesign: "Design Ui & Ux",
    developmentPageTitle: "Développment web et mobile",
    landingPages: "Pages statiques",
    portfolioWebsites: "Sites web portfolio",
    catalogWebsites: "Sites web catalogue ",
    eCommerce: "Plateformes e-commerce",
    webApps: "Applications Web",
    mobileApps: "Applications mobiles",
    quizNote: "Le devis sera envoyé par email",
    days: "Jours",
    requestQuote: "Demander un devis",
    quoteDesign: "Conception",
    quoteDevelopment: "Développement",
    quoteMarketing: "Marketing",
    quizDetails: "Détails",

    commercialProspecting: "Prospection commerciale",
    service5: 'Prospection commerciale',
    commercialP1: "Elle propose de prendre en main toutes les actions necessaires au",
    commercialP2: "Développement commercial",
    commercialStrategy: "Stratégie d'entreprise",
    multichannelProspecting: "Prospection multicanal",
    customerLoyalty: "Fidélisation clientèle",
    conquerNewMarket: "Conquérir de nouveaux marchés",

    prospectingP: "Experts de la prospection commerciale, Anytime & anywhere est spécialisée dans la détection d’opportunités d’affaires à forte valeur ajoutée et dans la prise de rendez-vous qualifiés B-to-B. Pour garantir son efficacité et sa qualité.",

    reviewsTitle: 'Avis clients',

    portfolio: [
        {
            name: "Valorant Boosting",
            photo: "valorant.png",
            url: "https://valorantboosting.herokuapp.com/",
        },
        {
            name: "DNL Deco",
            photo: "dnl.png",
            url: "https://dnl-deco.herokuapp.com/",
        },
        {
            name: "Dali Market",
            photo: "dalimarket.png",
            url: "https://dalimarket.tn/",
        },
        {
            name: "Pro Artl",
            photo: "pro-artl.png",
            url: "https://pro-artl.ru/",
        },
        {
            name: "Auto Dom Kst",
            photo: "autodomkst.png",
            url: "",
        },
        {
            name: "Barrist",
            photo: "barrist.png",
            url: "https://barrist.ru/",
        },
        {
            name: "Volkswagen Costanai",
            photo: "volkswagen-costanai.png",
            url: "https://vw.autodomkst.kz/",
        },
        {
            name: "Volkswagen Almaty",
            photo: "volkswagen-almaty.png",
            url: "https://volkswagen-almaty.kz/",
        },
        {
            name: "Retail Comiten",
            photo: "retail-comiten.png",
            url: "https://retail.comiten.ru/",
        },
        {
            name: "Zavodskaya Plitka",
            photo: "zavodskaya-plitka.png",
            url: "https://www.zavodskaya-plitka.ru/",
        },
        {
            name: "Aidapraznik",
            photo: "aidapraznik.png",
            url: "http://www.aidaprazdnik-dedmoroz.ru/",
        },
        {
            name: "Bahitgul Hotel",
            photo: "bahitgul.png",
            url: "https://bahitgul.com/",
        },
    ],

    jobs: [
        {
            ref: "WD0821",
            title: "Développeur Web",
            desc: "Développeur Full Stack, extrêmement polyvalent et capable de prendre en charge l'ensemble du processus de développement pour créer des sites web et des applications web & mobiles.",
            skills: [
                'Html', 'Css', 'JavaScript', 'ReactJS', 'NodeJs'
            ]
        },
        {
            ref: "DS0821",
            title: "Designer",
            desc: "Designer innovant qui peut créer une charte graphique complète pour une marque, ui et ux design et montage vidéo.",
            skills: [
                'Html', 'Css', 'JavaScript', 'ReactJS', 'NodeJs'
            ]
        },
        {
            ref: "CS0821",
            title: "Commerciale",
            desc: "Responsable du cycle de vente, vous déployez une stratégie intensive de prospection et accompagnez les prospects dans la définition de leur besoin.",
            skills: [
                'Html', 'Css', 'JavaScript', 'ReactJS', 'NodeJs'
            ]
        }
    ]
}

export const al = {
    lang: 'al',
    homePage: 'Startseite',
    aboutPage: 'Über uns',
    servicePage: 'Dienstleistungen',
    portfolioPage: 'Verweise',
    contactPage: 'Kontakt',
    devisBtn: 'Angebot anfordern',
    mainTitle: 'Take The Right Road',
    intro: "Anytime & Anywhere ist Ihr Geschäfts- und Anlageberater.",
    readMore: 'Weiterlesen',
    featuresTitle: 'Unser Vorgehen',
    featuresParag: 'Beschreibung des Prozesses, mit dem wir Ihr Unternehmen transformieren',
    design: 'Entwurf',
    development: 'Entwicklung',
    responsive: 'Ansprechend',
    seo: 'SEO',
    dataVisualTitle: 'Datenanalyse',
    dataTitle1: 'UNSER TEAM',
    dataParag1: "Unser kreatives, agiles und organisiertes Team widmet sich dem Erfolg Ihrer Projekte. Unser Unterschied liegt in unserer Fähigkeit, immer Lösungen anzubieten. Unser Team gewährleistet Ihnen eine einwandfreie Nachverfolgung vom Anfang bis zum Ende des Auftrags.",
    dataTitle2: '02. STRATEGIE',
    dataParag2: 'Nach einer Diagnosephase erstellen wir einen auf Ihre Bedürfnisse abgestimmten Aktionsplan.',
    itSolutionTitle: 'IT-Lösungen',
    itSolutionParag: 'Wir arbeiten mit Ihnen zusammen, um durch die digitale Transformation neue Werte zu schaffen. Wir haben Spezialisten zu Ihren Diensten.',
    serviceTitle: 'Unsere Dienstleistungen',
    service1: 'Vermarktungsstrategie',
    service2: 'Digitales Marketing',
    service3: 'Grafikdesign',
    service4: 'Web und Mobile Entwicklung',
    service1Point1: 'Kommunikationsstrategie',
    service1Point2: 'Medienplan',
    service1Point3: 'Werbekampagne',
    service2Point1: 'Webseiten-SEO',
    service2Point2: 'Sozialen Medien',
    service2Point3: 'Sponsoring',
    service3Point1: 'Identität, Logo, Visitenkarte ...',
    service3Point2: 'Poster, Katalog, Speisekarte ...',
    service3Point3: 'Webseiten- und Anwendungsdesign',
    service4Point1: 'Website-Entwicklung',
    service4Point2: 'Entwicklung von Web-Apps',
    service4Point3: 'Entwicklung mobiler Apps',
    managementServiceTitle: 'Service-Management',
    managementServiceParag: "Die Effizienz und Geschwindigkeit der Umwandlung von Rohdaten in zuverlässige und nützliche Informationen.",
    webAnalyticsTitle: 'Netz Analyse',
    webAnalyticsParag: 'Wir verbessern die Effizienz und überwachen den Erfolg Ihrer Website. Wir können Maßnahmen ableiten, die auf eine positive Entwicklung gemäß Ihren Zielen abzielen.',
    processTitle: 'Keine versteckten Kosten, Sie wählen den Tarif, der zu Ihnen passt',
    processParag: "Mit unseren Abo-Plänen wird Ihr Startgeld geschont und wir berechnen unsere Dienste mit dem maximalen Betrag bei der Bestellung: Sie zahlen, wenn es funktioniert!",
    ourPricesBtn: 'Unsere Preise',
    contactTitle: 'Entrer en contact',
    contactParag: "Wir richten Führungskräfte auf einen gemeinsamen Zweck und eine strategische Geschichte aus, die ihr Geschäft und ihre Marke zum Handeln anregen.",
    adressTitle: "Adresse",
    adress: "Rue ribat immeuble Meliene la corniche 4000 Sousse, Tunisie",
    emailTitle: "E-mail",
    email: "contact@anytime4anywhere.fr",
    phoneTitle: "Appeler nous",
    phone: "+21654563326",
    copyright: "2021 © Anytime & Anywhere",
    ourTeamTitle: 'Unser Team',
    about: "Die Mission von Anytime & Anywhere ist es, seine Kunden bei der Entwicklung ihrer Marketingstrategien zu unterstützen, indem ihnen kreative Konzepte und eine Reihe innovativer Lösungen angeboten werden, die auf ihre Bedürfnisse zugeschnitten sind. Digitale Kommunikation bietet Ihnen endlose Möglichkeiten. Unsere Agentur nutzt jede davon, um Sie zu sublimieren. Unsere Marketingagentur mit Sitz in Sousse, Tunesien, bietet Ihnen mehr als einen Webservice, ein globales Kommunikationsangebot.",
    nizar: 'Nizar Jerfel',
    nizarFunction: 'VORSITZENDER',
    faycel: 'Faycel Yousfi',
    faycelFunction: 'Technischer Direktor',
    maamoun: 'Maamoun Grissa',
    maamounFunction: 'Manager',
    kawther: 'Kawther Mehrez',
    kawtherFunction: 'Marketing Manager',
    elhem: 'Elhem Missaoui',
    elhemFunction: 'Entwickler',
    houssem: 'Houssem Jbely',
    houssemFunction: 'Designer',
    contactUs: "Kontaktiere uns",
    ourPortfolio: "Unser Portfolio",
    contactName: "Name",
    contactEmail: "Email",
    contactPhone: "Telefon",
    contactMessage: "Nachricht",
    sendBtn: "Senden",
    contactBtn: "kontaktiere uns",
    feedback_message: "Nachricht erfolgreich gesendet",
    feedback_error: "Fehler, bitte versuchen Sie es später noch einmal",
    whatsappMessage: "Willkommen bei Anytime Anywhere ist ein Beratungsunternehmen für die digitale Transformation. Wie können wir Ihnen helfen?",
    jobCity: "Sousse",
    jobSelect: "Auswählen",
    jobSelected : "Ausgewählt",
    jobSelectFile: "Wählen Sie Ihre Zusammenfassung",
    coverLettre: "Anschreiben",
    jobSelectedHolder: "Ausgewählte Stelle",
    joinProcess: "Wählen Sie einen Job und füllen Sie das Formular aus",
    marketingStrategy: "Marketingstrategie",
    strategyP1: "Die Marketingstrategie berücksichtigt das Umfeld eines Unternehmens und ermittelt seine Stärken und Schwächen, um kurz- und langfristige Geschäftspläne zu erstellen.",
    strategyP2: "Eine gut etablierte Marketingstrategie ist für jedes Unternehmen unerlässlich, um seine Handlungen konsequent und intelligent durchzuführen.",
    strategyP3: "Um wettbewerbsfähig zu bleiben, kommt Blindgehen nicht in Frage!",
    segmentation: "Segmentierung",
    targeting: "Ausrichtung",
    positioning: "Positionierung",
    smartGoals: "Smarte Ziele",
    marketWatch: "Marktbeobachtung und -studie",
    competitiveIntelligence: "Competitive Intelligence",
    marketingTarget: "Identifizierung des Marketingziels",
    marketingPosition: "Marketingposition",
    communicationStrategy: "Kommunikationsstrategie",
    digitalMarketing: "Digitales Marketing",
    seaSeo: "SEA & SEO",
    performanceMarketing: "Performance-Marketing",
    emailing: "E-Mail-Versand für Treue und Kundengewinnung",
    marketingPub: "Web- und Mobile-Werbung",
    marketingMedia: "Digital in die Medien integriert",
    marketingbtob: "B-to-B digitales Marketing, CRM",
    menuServices: "Dienste",
    graphicDesign: "Grafikdesign",
    visualIdentity: "Visuelle Identität",
    graphicaCharter: "Grafische Charta",
    paperSupports: "Papierstützen",
    exibitionSupports: "Ausstellungsträger",
    editingLayout: "Bearbeitung und Layout",
    UiUxDesign: "Ui- und Ux-Design",
    developmentPageTitle: "Web- und Mobile-Entwicklung",
    landingPages: "Landingpages",
    portfolioWebsites: "Portfolio-Websites",
    catalogWebsites: "Katalog-Websites",
    eCommerce: "E-Commerce-Plattformen",
    webApps: "Webanwendungen",
    mobileApps: "Mobile Anwendungen",
    quizNote: "Das Angebot wird per E-Mail verschickt",
    days: "Tage",
    requestQuote: "Angebot anfordern",
    quoteDesign: "Design",
    quoteDevelopment: "Entwicklung",
    quoteMarketing: "Marketing",
    quizDetails: "Einzelheiten",

    commercialProspecting: "Kommerzielle Prospektion",
    service5: 'Kommerzielle Prospektion',
    commercialP1: "Es schlägt vor, alle notwendigen Maßnahmen zu ergreifen",
    commercialP2: "Geschäftsentwicklung",
    commercialStrategy: "Kommerzielle Strategie",
    multichannelProspecting: "Multichannel-Prospecting",
    customerLoyalty: "Kundenbindung",
    conquerNewMarket: "Neue Märkte erobern",

    prospectingP: "Als Experte für Commercial Prospecting ist Anytime & Anytime auf die Erkennung von Geschäftsmöglichkeiten mit hohem Mehrwert und die Durchführung qualifizierter B-to-B-Meetings spezialisiert. Um seine Effizienz und Qualität zu garantieren.",

    reviewsTitle: 'Kundenbewertungen',

    portfolio: [
        {
            name: "Valorant Boosting",
            photo: "valorant.png",
            url: "https://valorantboosting.herokuapp.com/",
        },
        {
            name: "DNL Deco",
            photo: "dnl.png",
            url: "https://dnl-deco.herokuapp.com/",
        },
        {
            name: "Dali Market",
            photo: "dalimarket.png",
            url: "https://dalimarket.tn/",
        },
        {
            name: "Pro Artl",
            photo: "pro-artl.png",
            url: "https://pro-artl.ru/",
        },
        {
            name: "Auto Dom Kst",
            photo: "autodomkst.png",
            url: "",
        },
        {
            name: "Barrist",
            photo: "barrist.png",
            url: "https://barrist.ru/",
        },
        {
            name: "Volkswagen Costanai",
            photo: "volkswagen-costanai.png",
            url: "https://vw.autodomkst.kz/",
        },
        {
            name: "Volkswagen Almaty",
            photo: "volkswagen-almaty.png",
            url: "https://volkswagen-almaty.kz/",
        },
        {
            name: "Retail Comiten",
            photo: "retail-comiten.png",
            url: "https://retail.comiten.ru/",
        },
        {
            name: "Zavodskaya Plitka",
            photo: "zavodskaya-plitka.png",
            url: "https://www.zavodskaya-plitka.ru/",
        },
        {
            name: "Aidapraznik",
            photo: "aidapraznik.png",
            url: "http://www.aidaprazdnik-dedmoroz.ru/",
        },
        {
            name: "Bahitgul Hotel",
            photo: "bahitgul.png",
            url: "https://bahitgul.com/",
        },
    ],

    jobs: [
        {
            ref: "WD0821",
            title: "Web-Entwickler",
            desc: "Full-Stack-Entwickler, extrem vielseitig und in der Lage, den gesamten Entwicklungsprozess zur Bereitstellung von Websites und Web- und mobilen Anwendungen zu übernehmen.",
            skills: [
                'Html', 'Css', 'JavaScript', 'ReactJS', 'NodeJs'
            ]
        },
        {
            ref: "DS0821",
            title: "Designer",
            desc: "Innovativer Designer, der eine komplette Grafikcharta für eine Marke, UI- und UX-Design und Videobearbeitung erstellen kann.",
            skills: [
                'Html', 'Css', 'JavaScript', 'ReactJS', 'NodeJs'
            ]
        },
        {
            ref: "CS0821",
            title: "Werbung",
            desc: "Als Verantwortlicher für den Vertriebszyklus setzen Sie eine intensive Prospektionsstrategie um und unterstützen Interessenten bei der Bedarfsdefinition.",
            skills: [
                'Html', 'Css', 'JavaScript', 'ReactJS', 'NodeJs'
            ]
        }
    ]
}

export const ar = {
    lang: 'ar',
    homePage: 'الصفحة الرئيسبة',
    aboutPage: 'معلومات عنا',
    servicePage: 'خدمات',
    portfolioPage: 'مراجعنا',
    contactPage: 'اتصل بنا',
    devisBtn: 'طلب عرض أسعار',
    mainTitle: 'مستشاركم في الأعمال و الإستثمار',
    intro: "مهمتنا تمكينكم من معرفة ما هو ممكن، وتحقيق أهدافكم الإستثمارية و الريادة في مجال عملكم .",
    readMore: 'قراءة المزيد',
    featuresTitle: 'منهجنا',
    featuresParag: 'وصف للعملية التي نستخدمها لتحويل مشروعك',
    design: 'التصميم',
    development: 'التطوير والبرمجة',
    responsive: 'التجاوب مع جميع الأجهزة',
    seo: 'رتبتك في محركات البحث',
    dataVisualTitle: 'تحليل البيانات',
    dataTitle1: 'فريقنا',
    dataParag1: 'فريق عمل متميز و متكامل ذو خبرة واسعة في مجالات عدة، انطلاقا من خبراتنا في التسويق و جمع المعلومات  نضمن لحرفاءنا  إرساء استراتيجيات لتطوير أعمالهم و تسويق منتوجاتهم . لأننا ذوي معرفة ودراية واسعة في إدارة الأعمال فإننا نضمن سير الأمور بسلاسة و إبقاء حرفاءنا على المسار الصحيح ... بما أن العربية هي لغتنا الأم ، فإننا على اطلاع واسع بالأسواق العربية و زد على ذلك تمكننا من عدة لغات أخرى كالفرنسية و الأنجليزية.',
    dataTitle2: '02. الإستراتيجية',
    dataParag2: 'بعد مرحلة التشخيص ، سنضع خطة عمل تتكيف مع احتياجاتك.',
    itSolutionTitle: 'حلول تكنولوجيا المعلومات',
    itSolutionParag: 'نتعاون معك لخلق قيمة جديدة من خلال التحول الرقمي. لدينا متخصصون في خدماتك.',
    serviceTitle: 'خدماتنا',
    service1: 'استراتيجية التسويق',
    service2: 'التسويق الرقمي',
    service3: 'تصميم غرافيك',
    service4: 'برمجة الواب و الموبايل',
    service1Point1: 'خطط تواصل',
    service1Point2: 'خطط إعلامية',
    service1Point3: 'حملات إعلانية',
    service2Point1: 'المواقع SEO',
    service2Point2: 'وسائل التواصل الاجتماعي',
    service2Point3: 'رعاية',
    service3Point1: 'الهوية والشعار وبطاقة التعريف ...',
    service3Point2: 'ملصقات ، كتالوجات ، قائمات ...',
    service3Point3: 'تصميم المواقع والتطبيقات',
    service4Point1: 'برمجة المواقع الإلكترونية',
    service4Point2: 'برمجة تطبيقات الويب',
    service4Point3: 'تطوير تطبيقات الموبايل',
    managementServiceTitle: 'إدارة الخدمات',
    managementServiceParag: "كفاءة وسرعة تحويل البيانات الخام إلى معلومات موثوقة ومفيدة.",
    webAnalyticsTitle: 'تحليل الواب',
    webAnalyticsParag: 'نحن نحسن الكفاءة ونراقب نجاح موقع الويب الخاص بك. يمكننا استنتاج التدابير التي تهدف إلى إحداث تطور إيجابي وفقًا لأهدافك.',
    processTitle: 'بدون تكلفة خفية ، يمكنك اختيار السعر الذي يناسبك',
    processParag: "من خلال خطط الاشتراك الخاصة بنا ، يتم توفير نقودك عند بدء التشغيل ، ونقوم بشحن خدماتنا إلى أقصى مبلغ عند الطلب: أنت تدفع عندما تعمل!",
    ourPricesBtn: 'أسعارنا',
    contactTitle: 'ابقى على تواصل',
    contactParag: "نجمع القادة حول هدف مشترك وقصة استراتيجية تحفز أعمالهم وعلامتهم التجارية على اتخاذ الإجراءات اللازمة.",
    adressTitle: "العنوان",
    adress: "شارع الرباط غير القابل للذوبان مليان الكورنيش 4000 سوسة ، تونس",
    emailTitle: "البريد الإلكتروني",
    email: "contact@anytime4anywhere.fr",
    phoneTitle: "اتصل بنا",
    phone: "+21654563326",
    copyright: "2021 © Anytime & Anywhere",
    ourTeamTitle: 'فريقنا',
    about: "تتمثل مهمة Anytime & Anywhere في دعم عملائها في تطوير استراتيجياتهم التسويقية ، من خلال تزويدهم بمفاهيم إبداعية ومجموعة من الحلول المبتكرة المصممة لاحتياجاتهم. توفر لك الاتصالات الرقمية إمكانيات لا حصر لها ، تستخدم وكالتنا كل واحدة منهم لإضفاء المزيد من الرفاهية عليك. تقدم لك وكالتنا التسويقية ومقرها سوسة ، تونس ، أكثر من مجرد خدمة ويب ، عرض اتصال عالمي.",
    nizar: 'نزار جرفال',
    nizarFunction: 'المدير التنفيذي',
    faycel: 'فيصل اليوسفي',
    faycelFunction: 'مسؤول تقني',
    maamoun: 'المأمون قريسة',
    maamounFunction: 'مدير',
    kawther: 'كوثر محرز',
    kawtherFunction: 'مسؤول تسويق',
    elhem: 'إلهام الميساوي',
    elhemFunction: 'مبرمج',
    houssem: 'حسام الجبالي',
    houssemFunction: 'مصمم غرافيكي',
    contactUs: "تواصل معنا",
    ourPortfolio: "مراجعنا",
    contactName: "الاسم",
    contactEmail: "البريد الالكتروني",
    contactPhone: "الهاتف",
    contactMessage: "الرسالة",
    sendBtn: "ارسل",
    contactBtn: "اتصل بنا",
    feedback_message: "تم ارسال الرسالة بنجاح",
    feedback_error: "خطأ ، حاول مرة أخرى في وقت لاحق من فضلك",
    whatsappMessage: "مرحبًا بكم في آني تابم آني وار، هي شركة استشارية في التحول الرقمي ، كيف يمكننا مساعدتك؟",
    jobCity: "سوسة",
    jobSelect: "اختر",
    jobSelected : "المختار",
    jobSelectFile: "السيرة الذاتية",
    coverLettre: "رسالة تقديم",
    jobSelectedHolder: "الوظيفة المختارة",
    joinProcess: "اختر وظيفة واملأ الاستمارة",
    marketingStrategy: "استراتيجية التسويق",
    strategyP1: "تأخذ استراتيجية التسويق في الاعتبار بيئة الشركة ، وتحدد نقاط القوة والضعف فيها من أجل وضع خطط عمل قصيرة وطويلة المدى.",
    strategyP2: "استراتيجية التسويق الراسخة ضرورية لأي شركة من أجل تنفيذ أعمالها بثبات وذكاء.",
    strategyP3: "لأن الاستمرار في المنافسة ، فإن فقدان البصر أمر غير وارد!",
    segmentation: "تجزئة",
    targeting: "الاستهداف",
    positioning: "تحديد المواقع",
    smartGoals: "أهداف ذكية",
    marketWatch: "مراقبة السوق ودراسته",
    competitiveIntelligence: "الذكاء التنافسي",
    marketingTarget: "تحديد هدف التسويق",
    marketingPosition: "موقع التسويق",
    communicationStrategy: "استراتيجية الاتصال",
    digitalMarketing: "التسويق الرقمي",
    seaSeo: "تحسين ترتيب محركات البحث",
    performanceMarketing: "تحسين آداء التسويق",
    emailing: "التسويق بالبريد الإلكتروني",
    marketingPub: "إعلانات الويب والجوال",
    marketingMedia: "التسويق الرقمي في وسائل الاعلام",
    marketingbtob: " B-to-B, CRM التحول الرقمي",
    menuServices: "الخدمات",
    graphicDesign: "التصميم الجرافيكي",
    visualIdentity: "الهوية المرئية",
    graphicaCharter: "ميثاق رسومي",
    paperSupports: "تصاميم الأوراق",
    exibitionSupports: "تصاميم العرض",
    editingLayout: "التحرير و التخطيط",
    UiUxDesign: "Ui & Ux تصميم",
    developmentPageTitle: "تطوير الويب والجوال",
    landingPages: "صفحات ثابتة",
    portfolioWebsites: "المواقع المحفضة",
    catalogWebsites: "المواقع الكتالوج",
    eCommerce: "منصات التجارة الالكترونية",
    webApps: "تطبيقات الواب",
    mobileApps: "تطبيقات الجوال",
    quizNote: "سيتم إرسال عرض الأسعار عبر البريد الإلكتروني",
    days: "أيام",
    requestQuote: "طلب عرض أسعار",
    quoteDesign: "تخطيط",
    quoteDevelopment: "برمجة",
    quoteMarketing: "تسويق",
    quizDetails: "تفاصيل",

    commercialProspecting: "التنقيب التجاري",
    service5: 'التنقيب التجاري',
    commercialP1: "يقترح أن تأخذ في متناول اليد جميع الإجراءات اللازمة في ",
    commercialP2: "طوير الأعمال",
    commercialStrategy: "الإستراتيجية التجارية",
    multichannelProspecting: "التنقيب متعدد القنوات",
    customerLoyalty: "ولاء العميل",
    conquerNewMarket: "جلب أسواق جديدة",

    prospectingP: "خبراء في التنقيب التجاري ، في أي وقت وفي أي مكان متخصصون في الكشف عن فرص العمل ذات القيمة المضافة العالية وفي عقد اجتماعات B-to-B المؤهلة. لضمان كفاءتها وجودتها.",

    reviewsTitle: 'تعاليق العملاء',

    portfolio: [
        {
            name: "Valorant Boosting",
            photo: "valorant.png",
            url: "https://valorantboosting.herokuapp.com/",
        },
        {
            name: "DNL Deco",
            photo: "dnl.png",
            url: "https://dnl-deco.herokuapp.com/",
        },
        {
            name: "Dali Market",
            photo: "dalimarket.png",
            url: "https://dalimarket.tn/",
        },
        {
            name: "Pro Artl",
            photo: "pro-artl.png",
            url: "https://pro-artl.ru/",
        },
        {
            name: "Auto Dom Kst",
            photo: "autodomkst.png",
            url: "",
        },
        {
            name: "Barrist",
            photo: "barrist.png",
            url: "https://barrist.ru/",
        },
        {
            name: "Volkswagen Costanai",
            photo: "volkswagen-costanai.png",
            url: "https://vw.autodomkst.kz/",
        },
        {
            name: "Volkswagen Almaty",
            photo: "volkswagen-almaty.png",
            url: "https://volkswagen-almaty.kz/",
        },
        {
            name: "Retail Comiten",
            photo: "retail-comiten.png",
            url: "https://retail.comiten.ru/",
        },
        {
            name: "Zavodskaya Plitka",
            photo: "zavodskaya-plitka.png",
            url: "https://www.zavodskaya-plitka.ru/",
        },
        {
            name: "Aidapraznik",
            photo: "aidapraznik.png",
            url: "http://www.aidaprazdnik-dedmoroz.ru/",
        },
        {
            name: "Bahitgul Hotel",
            photo: "bahitgul.png",
            url: "https://bahitgul.com/",
        },
    ],

    jobs: [
        {
            ref: "WD0821",
            title: "مبرمج واب",
            desc: "مطور Full Stack ، متعدد الاستخدامات للغاية وقادر على تحمل مسؤولية عملية التطوير بأكملها لتوفير مواقع الويب وتطبيقات الويب والجوال.",
            skills: [
                'Html', 'Css', 'JavaScript', 'ReactJS', 'NodeJs'
            ]
        },
        {
            ref: "DS0821",
            title: "مصمم",
            desc: "مصمم مبتكر يمكنه إنشاء ميثاق رسومي كامل للعلامة التجارية وتصميم Ui و UX وتحرير الفيديو.",
            skills: [
                'Html', 'Css', 'JavaScript', 'ReactJS', 'NodeJs'
            ]
        },
        {
            ref: "CS0821",
            title: "مسؤول تجاري",
            desc: "مسؤول عن دورة المبيعات ، وتقوم بنشر استراتيجية بحث مكثفة ودعم العملاء المحتملين في تحديد احتياجاتهم.",
            skills: [
                'Html', 'Css', 'JavaScript', 'ReactJS', 'NodeJs'
            ]
        }
    ]
}